name: Java CI

on: [ push, workflow_dispatch ]

env:
  SPP_PROBE_WAIT_FOR_PLATFORM: "true"
  SPP_PROBE_PLATFORM_HOST: "https://cloud.sourceplus.plus"
  SPP_PROBE_SSL_ENABLED: "true"
  SPP_PROBE_CLIENT_ID: "spp_ci_pycVI2zIryWRtymsLnHXx39aM88c1Yi6jJYEFw306iFUXTczlx"
  SPP_PROBE_CLIENT_SECRET: "spp_cs_8aVVsJdFFXMy6l3LO2336KGg4mQa1gmExyxBmAOjOpLFOL997V"
  SPP_PROBE_TENANT_ID: "tenant1"
  SPP_PROBE_PLATFORM_CERTIFICATE: "MIIFODCCBCCgAwIBAgISA45itGRYnufLiVcFw8EgiPRMMA0GCSqGSIb3DQEBCwUAMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJSMzAeFw0yMzA1MDcwODE0NTRaFw0yMzA4MDUwODE0NTNaMBwxGjAYBgNVBAMMESouc291cmNlcGx1cy5wbHVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4f8YdDxiiXWHRnNOgm6saybvK7v8nMZtYcOFAWhQUnjycmPiyCfcboGupr+9ADLYGXILn1oIhrNTjXNnXG2w/9gOVJ7WkuBWD0+2rOoaAyau7fyV+2m6HOhcxwQ+qhFQdh8kl0qHWZ2LrI4uSFcuqt0B41eezDflYZuAHuLAU9KVOco8XT+k1NzN0QlVLdsZQWuloDlCyhVlK4yHd2mWWw7UkmOrlH1cUDIwfew5mbnPAiu0L9lc9hgG5kjz8smwQb1DjcMPEK5ZiCSuxY/O9dKQ9EOHIzWcJCBvqAi772AkrKCZD62eFajjfWvx2GC10z3KmYT2ECMQAmwVhbB06wIDAQABo4ICXDCCAlgwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBSFRQdHcS8vLRDrDF6kB99LKWLpgDAfBgNVHSMEGDAWgBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYBBQUHMAGGFWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3IzLmkubGVuY3Iub3JnLzAtBgNVHREEJjAkghEqLnNvdXJjZXBsdXMucGx1c4IPc291cmNlcGx1cy5wbHVzMEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBAwYKKwYBBAHWeQIEAgSB9ASB8QDvAHYAtz77JN+cTbp18jnFulj0bF38Qs96nzXEnh0JgSXttJkAAAGH9X4YCAAABAMARzBFAiEA6yCnWtuQo2nalzx1q21E3kjoArvrItZhjCfhRJQBo0wCIHCN9lEiCrVg+V0ctbpaLaetFlFMuXy7zFBar+b4Dk6/AHUAejKMVNi3LbYg6jjgUh7phBZwMhOFTTvSK8E6V6NS61IAAAGH9X4YGgAABAMARjBEAiBxm8VIH5TQQoPtwDvSsDmYOzapT2DqNK97nLlhFNBvOwIgMsbKkpW8bJmUZD79e6GezpRhnoLtU+uyM/nfAqfU3SgwDQYJKoZIhvcNAQELBQADggEBAEMKMWnV4F0Leb1tcJ10YqN0unaqB1UKg3VchF3jiQAVxtZC8oKG7THkMOgWmFb1QVdCKqyF90kRH45lx6fuNCCG5EztOXxZhyzymh44Ql61w2ssL8wsgps+4byrTUh2cvR5sjK1wS6ZMscTi+m0hbj0Z78U39cDb66nVgQmowYelGizAM1I/VBiOunetTIE9PRSBGdyPEtGLbnd0wsW1UK2mIaTgVLITRdh4ddHqaHzjpuxoiVX7m57gQw/14sKNxBv5DldIMbWPfI7mTiIKAsQfDEMpsrWMV+SVDUkcex4QBk7vDW3qzS2GdB2nrBFxFYvdfFQA+/CvPuMb8qFI30="

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: |
          echo "SPP_APPLICATION_GIT_COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "SPP_APPLICATION_ENVIRONMENT=ci" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
      - name: Upload skywalking-api.log
        if: ${{ always() }}
        run: |
          ls -l /tmp/spp-probe
      - name: Upload skywalking-api.log
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: skywalking-api.log
          path: /tmp/spp-probe/logs/skywalking-api.log
