name: Java CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' #run every hour

env:
  SPP_PROBE_PLATFORM_HOST: "https://cloud.sourceplus.plus"
  SPP_PROBE_SSL_ENABLED: "true"
  SPP_PROBE_CLIENT_ID: "spp_ci_pycVI2zIryWRtymsLnHXx39aM88c1Yi6jJYEFw306iFUXTczlx"
  SPP_PROBE_CLIENT_SECRET: "spp_cs_8aVVsJdFFXMy6l3LO2336KGg4mQa1gmExyxBmAOjOpLFOL997V"
  SPP_PROBE_TENANT_ID: "tenant1"
  SPP_PROBE_PLATFORM_CERTIFICATE: "MIIFATCCA+mgAwIBAgISAxrdHsJWKQR5qCnBi9/fU2VqMA0GCSqGSIb3DQEBCwUAMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJSMzAeFw0yMzA3MDYwNzE3MDVaFw0yMzEwMDQwNzE3MDRaMBwxGjAYBgNVBAMMESouc291cmNlcGx1cy5wbHVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4f8YdDxiiXWHRnNOgm6saybvK7v8nMZtYcOFAWhQUnjycmPiyCfcboGupr+9ADLYGXILn1oIhrNTjXNnXG2w/9gOVJ7WkuBWD0+2rOoaAyau7fyV+2m6HOhcxwQ+qhFQdh8kl0qHWZ2LrI4uSFcuqt0B41eezDflYZuAHuLAU9KVOco8XT+k1NzN0QlVLdsZQWuloDlCyhVlK4yHd2mWWw7UkmOrlH1cUDIwfew5mbnPAiu0L9lc9hgG5kjz8smwQb1DjcMPEK5ZiCSuxY/O9dKQ9EOHIzWcJCBvqAi772AkrKCZD62eFajjfWvx2GC10z3KmYT2ECMQAmwVhbB06wIDAQABo4ICJTCCAiEwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBSFRQdHcS8vLRDrDF6kB99LKWLpgDAfBgNVHSMEGDAWgBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYBBQUHMAGGFWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3IzLmkubGVuY3Iub3JnLzAtBgNVHREEJjAkghEqLnNvdXJjZXBsdXMucGx1c4IPc291cmNlcGx1cy5wbHVzMBMGA1UdIAQMMAowCAYGZ4EMAQIBMIIBBQYKKwYBBAHWeQIEAgSB9gSB8wDxAHcAejKMVNi3LbYg6jjgUh7phBZwMhOFTTvSK8E6V6NS61IAAAGJKka5pQAABAMASDBGAiEAi4naGqFDPKx2IB7QP7Q7KUcfoA1KtF1jcQ3+GkrHXMcCIQCdWMjhB/7WIUstRB4IPq+ajzUkliRBCxnZ+dUnGt+ZoQB2AOg+0No+9QY1MudXKLyJa8kD08vREWvs62nhd31tBr1uAAABiSpGubQAAAQDAEcwRQIhAId384uzZ9TCnS73wewYf0d2YJuSriN2sGH2yXeP3RMCAiBbKQFZhulTo5o4iygZH3ba7v73Hlke2I5RCusMbPv4ojANBgkqhkiG9w0BAQsFAAOCAQEAhldOuOPwWiQTP5+FQjaaxJKHWL8Vya8kT0tCibBnAVerjagxh08YsPIZ4sKRtDbdzgfKOVagixbv17V+xhbsy05efdIEUofB182miJynx/GnfS3crfAd7CJhEWzCwoYk61btVD8hlhCrtxjMijIuJ8ci2nkF4y4w+vLk6TBfrkExhoAJYpY7v1PMRo3buSoA3VEFwTey2LZVR6LBRRwfgpWHLbS8hWTxSRSSixJ7kmCE0IO14efqvJDMyxhxhobiocb0/BSMWU/CrJn3dhO8M/Lb5x//npRu+wRtVqii4cUCCamCdio2DY1Qh3zhANMZNiBxoRpSJGNkurzKghmy1Q=="

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: |
          echo "SPP_APPLICATION_ENVIRONMENT=ci" >> $GITHUB_ENV
          echo "SPP_APPLICATION_VERSION=${GITHUB_SHA}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        continue-on-error: true
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
      - name: Upload skywalking-api.log
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: skywalking-api.log
          path: /tmp/spp-probe/logs/skywalking-api.log
